spring:
  datasource:
    url: jdbc:postgresql://db.zrspwxwehpbzivgvieso.supabase.co:5432/postgres
    username: postgres
    password: 8UKdn4Gs6KNYjM6i
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            "[non_contextual_creation]": true
    hibernate:
      ddl-auto: create

  profiles:
    active:
      - db
  servlet:
    multipart:
      max-file-size: 10MB
application:
  security:
    jwt:
      expiration: 86400000
      refresh-token:
        expiration: 604800000
      secret-key: UcbGQCpxBsZ8aQLUeLFWLOodKEoznGKIC9+rXBdorE4=