name: Deployment to aws
on:
    push:
        branches:
            - main
            - deploy


jobs:
    build-frontend:
        name: build-frontend
        runs-on: ubuntu-latest
        steps:
            -
                name: checkout
                uses: actions/checkout@v3

            -
                name: Set up QEMU
                uses: docker/setup-qemu-action@v2
            -
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2
            -
                name: Login to DockerHub
                uses: docker/login-action@v2
                with:
                    username: ${{ secrets.DOCKER_HUB_USERNAME }}
                    password: ${{ secrets.DOCKER_HUB_TOKEN }}
            -
                name: Build and push
                uses: docker/build-push-action@v4
                with:
                    push: true
                    tags: ${{ secrets.DOCKER_HUB_USERNAME }}/student-connect-fe:latest
                    context: ./kaew-wan-frontend

    build-backend:
        name: build-backend
        runs-on: ubuntu-latest
        steps:
            -
              name: checkout
              uses: actions/checkout@v2
            -
              name: setup Java
              uses: actions/setup-java@v3
              with:
                java-version: '17'
                distribution: 'adopt'
            -
              name: run Maven
              run: |
                echo "${{ secrets.JWT_PRIVATE_KEY }}" | tr -d '\r' > src/main/resources/jwt.pem
                echo "${{ secrets.JWT_PUBLIC_KEY }}" | tr -d '\r' > src/main/resources/jwt.pub.pem
                mvn clean install -DskipTests -B
                mkdir -p target/dependency && (cd target/dependency; unzip ../*.jar)
              working-directory: ./kaew-wan-backend
            -
              name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            -
              name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            -
              name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_HUB_USERNAME }}
                password: ${{ secrets.DOCKER_HUB_TOKEN }}
            -
              name: Build and push
              uses: docker/build-push-action@v4
              with:
                push: true
                tags: ${{ secrets.DOCKER_HUB_USERNAME }}/student-connect-be:latest
                context: ./kaew-wan-backend


    deploy-to-aws:
        needs: [build-frontend,build-backend]
        runs-on: ubuntu-latest
        env:
            DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        steps:
            -
                name: checkout
                uses: actions/checkout@v2
            -
                name: Copy file via ssh password
                uses: appleboy/scp-action@v0.1.4
                with:
                    host: ${{ secrets.HOST_SERVER }}
                    username: ${{ secrets.HOST_USERNAME }}
                    key: ${{ secrets.PRIVATE_KEY }}
                    port: 22
                    source: "docker-compose.yml"
                    target: "/home/ubuntu/kaew-wan"
            -
                name: docker compose
                uses: appleboy/ssh-action@v0.1.10
                with:
                    host: ${{ secrets.HOST_SERVER }}
                    username: ${{ secrets.HOST_USERNAME }}
                    key: ${{ secrets.PRIVATE_KEY }}
                    port: 22
                    script: |
                        export DOCKER_HUB_USERNAME=${{ secrets.DOCKER_HUB_USERNAME }}
                        cd /home/ubuntu/kaew-wan
                        echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
                        docker compose down
                        docker compose pull
                        docker compose up -d
                        rm -rf /home/ubuntu/kaew-wan
