name: Deployment to aws
on: 
    push:
        branches:
            - dev
            - deploy

jobs: 
    build-frontend:
        name: build-fe
        runs-on: ubuntu-latest   
        steps:
            -
                name: checkout
                uses: actions/checkout@v3
                
            -
                name: Set up QEMU
                uses: docker/setup-qemu-action@v2
            -
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2
            -
                name: Login to DockerHub
                uses: docker/login-action@v2
                with:
                    username: ${{ secrets.DOCKER_HUB_USERNAME }}
                    password: ${{ secrets.DOCKER_HUB_TOKEN }}
            -
                name: Build and push
                uses: docker/build-push-action@v4
                with:
                    push: true
                    tags: ${{ secrets.DOCKER_HUB_USERNAME }}/student-connect-fe:latest
                    context: ./kaew-wan-frontend
    
    build-backend:
        name: build-be
        runs-on: ubuntu-latest
        steps:
            -
              name: checkout
              uses: actions/checkout@v2
            -
              name: setup Java
              uses: actions/setup-java@v3
              with:
                java-version: '17'
                distribution: 'adopt'
            -
              name: run Maven
              run: |
                mvn clean install -DskipTests -B
                mkdir -p target/dependency && (cd target/dependency; unzip ../*.jar)
              working-directory: ./kaew-wan-backend
            - 
              name: Set up QEMU
              uses: docker/setup-qemu-action@v2
            -
              name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2
            - 
              name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_HUB_USERNAME }}
                password: ${{ secrets.DOCKER_HUB_TOKEN }}
            -
              name: Build and push
              uses: docker/build-push-action@v4
              with:
                push: true
                tags: ${{ secrets.DOCKER_HUB_USERNAME }}/student-connect-be:latest
                context: ./kaew-wan-backend



